### PR TITLE
Remove Gemfile.lock

### PR DESCRIPTION
**Pull request by tmaier**
Tests failed for me, as the Gemfile.lock was outdated.

It is not recommended to commit the Gemfile.lock when developing gems.

### CODE REVIEW

**Comment by mapreal19** [comment]
@tmaier I disagree. From https://bundler.io/guides/faq.html

> Q: Should I commit my `Gemfile.lock` when writing a gem?
> 
> A: Yes, you should commit it. The presence of a `Gemfile.lock` in a gem's repository ensures that a fresh checkout of the repository uses the exact same set of dependencies every time. We believe this makes repositories more friendly towards new and existing contributors. Ideally, anyone should be able to clone the repo, run `bundle install`, and have passing tests. If you don't check in your `Gemfile.lock`, new contributors can get different versions of your dependencies, and run into failing tests that they don't know how to fix.

It is better to update the Gemfile.lock then and not remove it as a quick fix. cc @inukshuk

**Comment by tmaier** [comment]
You are absolutely right. I was acting based on an outdated information.. I am going to revert this.

Is it ok to just run `bundle update` or are special measures necessary?

**Comment by inukshuk** [comment]
Thanks @mapreal19 -- yes I think it's OK to leave lock file in the repository ([it's excluded from the manifest file](https://github.com/inukshuk/bibtex-ruby/blob/master/Rakefile#L85) and thus excluded from the Gem).

**Comment by inukshuk** [comment]
With regard to `bundle update` there's no special measures involved that I can think of? The main issue is probably that the entire stack is very old. Generally, all dependencies are not really crucial, because they are 'only' used for development or testing (or for converting to other formats). But because there are quite a lot of tests and scripts updating or changing some of these can turn into a chore.

**Pull request merged**
