### PR TITLE
Rewrite name_parser for Japanese, Korean and Chinese support. 

### PR DESCRIPTION
**Pull request by grafi-tt**
I rewrited name_parser for Japanese, Korean and Chinese support. Test for Japanese names are also added. All tests are passed in Ruby 2.2.

In these language, names are written in <surname> <givenname>.
BibTeX files written in such a manner are popular in Japan.
Switching yacc's grammer by detected letters is hard. Therefore the new parser
is hand-written (tokenizing parts are roughly based on the original implementation).

The new parser also supports better error reporting.

## note on testing
In Ruby 1.8 letter detection, using Oniguruma's unicode functionality, is not working. Therefore added tests should be disabled on Ruby 1.8. However now it is just added because I don't know how to achieve that.

### CODE REVIEW

**Comment by grafi-tt** [comment]
Sorry that travis-ci reports this is not working on Ruby 1.9.3. I'll investigate the cause and fix soon.

**Comment by inukshuk** [comment]
Thanks for contributing!

Can you explain why the parser does not work for Japanese names? Is it only because of the order of first and last name? If so, couldn't we just detect those names based on their unicode point range (i.e., if the name contains kanji anywhere and use a dedicated parser alternative for those?

I'm not against switching our the parser completely in principle, but in that case I'd need help with maintaining the code going forward.

Somewhat unrelated, the name parser was the basis for https://github.com/bermancenter/namae and I've been thinking of just using that gem in for bibtex-ruby; in any case, it would be cool if we could improve support for Asian names in namae and then use that instead (wishful thinking).

**Comment by grafi-tt** [comment]
Thank you for your comments! Actually it turned out fairly good implementation by racc, with relatively small modifications is possible. I'll create a new pull request soon.

Let me explain the reason I thought it isn't straightforward.
Author field may have mixed ordered names, e.g. Japanese person and English person. Therefore two dedicated parsers for all the author field don't suffice. Though it is possible to run racc parser individually for each person's name, it also requires fairly large changes. In addition, the racc parser just for one name seemed overwhelming for me.

In new pull request, the changes on the tokenizer will be little. In this pull request it was largely changed, because 1) tricky lower word position detection is required, and 2) I was not conservative since there were already many changes.

**Comment by grafi-tt** [comment]
By the way https://github.com/bermancenter/namae is not accessible (404 error). I googled but I was not able to find the mentioned library.

**Comment by inukshuk** [comment]
Sorry about that, the correct link is https://github.com/berkmancenter/namae

**Pull request closed without merging**
